 <?php
 
 $title = 'Deletar Cliente';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Tem certeza que quer deletar o cliente?
     '<?php echo $this->escapeHtml($fidoti->nome); ?>'
 </p>
 <?php
 $url = $this->url('fidoti', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $fidoti->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>