<?php
 
 $title = 'Editar Produto';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'fidoti',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

echo "<table>";

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome')) . "<br>";
echo $this->formRow($form->get('telefone')) . "<br>";
echo $this->formRow($form->get('celular')) . "<br>";
echo $this->formRow($form->get('endereco')) . "<br>";
echo $this->formRow($form->get('email')) . "<br>";
echo $this->formRow($form->get('servico')) . "<br>";
echo $this->formRow($form->get('descricao')) . "<br>";
echo $this->formRow($form->get('tipo')) . "<br>";
echo $this->formRow($form->get('produto')) . "<br>";
echo $this->formRow($form->get('valor')) . "<br>";
echo $this->formRow($form->get('data_retirada')) . "<br>";
echo $this->formRow($form->get('data_entrega')) . "<br>"; 
echo $this->formRow($form->get('forma_pagamento')) . "<br>";
echo $this->formRow($form->get('obs')) . "<br>";
echo $this->formRow($form->get('data')) . "<br>";
echo $this->formSubmit($form->get('submit')) . "<br>";
echo $this->form()->closeTag();

echo "</table>";