<?php
 
 $title = 'Editar Produto';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'produto',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('codigo'));
echo $this->formRow($form->get('genero'));
echo $this->formRow($form->get('quantidade'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();