<html>
<head>
 <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/tinymce/tinymce.min.js');
?>

<?php

 $title = 'Edição album';
 $this->headTitle($title);
 ?>

  <h1><?php echo $this->escapeHtml($title); ?></h1>

</head>

<script>  
tinyMCE.init({  
selector: "textarea",
theme : "modern",  
mode : "exact",  
elements : "template",  
width : "580",  
height: "200",  
plugins : "paste, table",  
theme_advanced_resizing : true,  
theme_advanced_resizing_use_cookie : false,  
theme_advanced_toolbar_location : "top",  
theme_advanced_buttons1 : "formatselect, bold, italic, underline, strikethrough, |, justifyleft, justifycenter, justifyright, justifyfull, |, bullist, numlist, |, outdent, indent, blockquote, |, undo, redo, cleanup, removeformat, pasteword, code ",  
theme_advanced_buttons2 : "link, unlink, anchor, |, image, hr , sub, sup, charmap, |, forecolor, backcolor, |, tablecontrols",  
theme_advanced_buttons3 : "",  
theme_advanced_blockformats : "p,h1,h2,h3,blockquote,dt,dd"  
});  
</script> 

<body>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'album',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'));
 echo "<br><br><br>" . $this->formRow($form->get('artist'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();

?>
 </body>
 </html>

